const MAX_FILM_DURATION = 40
const NUMBER_MOVIES_DESKTOP = 4
const NUMBER_MOVIES_TABLET = 2
const NUMBER_MOVIES_MOBIL = 2
const PATTERN_REGEX_EMAIL = "[a-zA-Z0-9_.]+@[a-zA-Z0-9_]+\\.[a-z]{2,}"
export {
  MAX_FILM_DURATION,
  NUMBER_MOVIES_DESKTOP,
  NUMBER_MOVIES_TABLET,
  NUMBER_MOVIES_MOBIL,
  PATTERN_REGEX_EMAIL,
}
